eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/song-microservice/protocol/openid-connect/token