spring:
  datasource:
    url: jdbc:postgresql://postgres_container:5432/file_api_db
    username: postgres
    password: postgres11
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/song-microservice
          jwk-set-uri: http://keycloak:8080/realms/song-microservice/protocol/openid-connect/certs
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://keycloak:8080/realms/song-microservice
#            user-name-attribute: preferred_username

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka