spring:
  datasource:
    url: jdbc:postgresql://postgres_container:5432/file_api_db
    username: postgres
    password: postgres11

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka