spring:
  datasource:
    url: jdbc:postgresql://postgres_container:5432/file_api_db
    username: postgres
    password: postgres11
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/song-microservice
          jwk-set-uri: http://keycloak:8080/realms/song-microservice/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/song-microservice/protocol/openid-connect/token
  rabbitmq:
    host: rabbitmq
    port: 5672
    
  data:
    mongodb:
      host: mongodb
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

minio:
  endpoint: http://minio:9000
