spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/song_api_db
    username: postgres
    password: postgres11
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/song-microservice
          jwk-set-uri: http://localhost:8080/realms/song-microservice/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      client-id: song-api
      principal-attribute: preferred_username

camel:
  component:
    aws2-sqs:
      access-key: AKIAIOSFODNN7EXAMPLE
      secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      region: eu-west-1
      override-endpoint: true
      uri-endpoint-override: http://awslocal:4566

server:
  port: 11000
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

delay: 1000
consumer-queue: enricher-song-queue