camel:
  component:
    aws2-sqs:
      access-key: AKIAIOSFODNN7EXAMPLE
      secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      region: eu-west-1
      override-endpoint: true
      uri-endpoint-override: http://awslocal:4566

server:
  port: 10000
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

delay: 1000
consumer-queue: file-enricher-queue
producer-queue: enricher-song-queue

file-api-name: file-api

spotify:
  client-id: 4a67fa16eb1943e581d4853135ad4099
  client-secret: 69d6db9055c64ed88c3fbafcb84227d5
  token-endpoint: https://accounts.spotify.com/api/token